export const PAYPALYCH_NOTIFICATION_SUCCESS_STATUS = 'SUCCESS';
export const PAYPALYCH_NOTIFICATION_FAIL_STATUS = 'FAIL';
export const PAYPALYCH_PAYMENT_SYSTEM = 'PAYPALYCH';
export const FREEKASSA_PAYMENT_SYSTEM = 'FREEKASSA';
